### ISSUE TITLE
Precision, Recall

### ISSUE THREAD

**Issue by ashkan-software** [sid-devic/rddnn#2]
need to print Precision and Recall in addition to accuracy.

**Comment by sid-devic** [comment]
I have added precision and recall to the `test()` function that you call within the `failure_iteration.py` code. If you would like to log precision, recall and average them for different models, could you please add the code to `failure_iteration.py`? Assume that `test()` returns a 3-tuple: `(accuracy, recall, precision)`. An example would be the 3-tuple: `(.925123, .9233, .9437)`. I have implemented this new `test()` method in `restore_activeGuard.py`, it is at the bottom of the code and you should be able to see what kind of data you are getting.

**Comment by sid-devic** [comment]
Implemented.
