### ISSUE TITLE
Automate the best test data split

### ISSUE THREAD

**Issue by ashkan-software** [sid-devic/rddnn#3]
Instead of manually deciding whether a balanced vs. unbalanced dataset is better and more suitable for testing, making it automatic. (maybe test both cases (balanced vs. unbalanced dataset for test) and print the accuracy, precision, and recall for both)

**Comment by ashkan-software** [comment]
Instead of coding this (automatic the best test data split), we can try on different cases and if  in all cases unbalanced is better, just keep the unbalanced case and forget automating it

**Comment by sid-devic** [comment]
I can automate this easily by making the `test()` function return 2, 3-tuples: one for the unbalanced case and one for the balanced case. On your end, you can assume you will get an array `[unbalanced, balanced]` where unbalanced and balanced are 3-tuples with `(acc, recall, precision)`. Modify `failure_iteration.py`, i'm not sure what you wanted to do with all the new data i'm giving you from the model.

**Comment by ashkan-software** [comment]
the test() function return 2, 3-tuples
