### ISSUE TITLE
Test the activeGuard with our fixed weight

### ISSUE THREAD

**Issue by ashkan-software** [sid-devic/rddnn#4]
Test the activeGuard method (fixed weights, while failing layers during training) with our method of fixed weights (rather than using weight of 1) and see what happens.

**Comment by sid-devic** [comment]
I have coded this method, and called it fixedActiveGuard. It's associated files are fixedActiveGuard_train.py, and restore_fixedActiveGuard.py. Here are some preliminary results, using the same survivability vector as the one used to test activePatrol:

|  Run 	|   Valset acc	|   failure_iteration acc	|   npseed, tfseed	|   
|---	|---	|---	|---	|
|1   	|   98.3%	| 81.6486%  	| 8433, 3505  	|
|  2 	|   96.0%	|   89.932%	|   2332, 4811	|   	
|   3	|   96.9%	|  84.5365%	|   672, 9780	|   	
|   4	|   99.3%	|   93.6935%	|   4896, 4010	|   	
|   5	|   99.1%	|   93.3107%	|   1994, 8923	|   	

Looks like it could turn out to be an improvement if we select the best performing model (which is a common thing to do for machine learning papers).
